version: '3.8'

services:
  gosafe-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gosafe-backend-app
    ports:
      - "8080:8080"
    environment:
      # Database connection configurations.
      # NOTE: For local execution, replace the URL with your external connection string,
      # as the internal hostname 'dpg-d96eege7r5hc7389sgvg-a' only resolves inside Render's network.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d96eege7r5hc7389sgvg-a:5432/gosafe_db
      - SPRING_DATASOURCE_USERNAME=gosafe_db_user
      - SPRING_DATASOURCE_PASSWORD=U6xyQeJGxVPAIWj2fiXrHCRPc8UFcRuE
      - GOSAFE_JWTSECRET=gosafeSecretKeyJWTForAuthenticationNeedsToBeLongEnoughForHMAC256AndSecureEnoughForProductionUse!
    restart: unless-stopped
