server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d96eege7r5hc7389sgvg-a:5432/gosafe-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gosafe_db_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:U6xyQeJGxVPAIWj2fiXrHCRPc8UFcRuE}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update

# JWT security configuration
gosafe.jwtSecret=gosafeSecretKeyJWTForAuthenticationNeedsToBeLongEnoughForHMAC256AndSecureEnoughForProductionUse!
gosafe.jwtExpirationMs=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
